// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import "time"



type Event struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	DateTime    string  `json:"dateTime"`
	Organizer   *User   `json:"organizer"`
	Subscribers []*User `json:"subscribers"`
	CreatedAt   time.Time  `json:"createdAt" bson:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Email         string          `json:"email"`
	Subscriptions []*Subscription `json:"subscriptions"`
	CreatedAt   time.Time  `json:"createdAt" bson:"createdAt"`

}
