// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	DateTime    string  `json:"dateTime"`
	Organizer   *User   `json:"organizer"`
	Subscribers []*User `json:"subscribers"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
    ID              string  `json:"id"`
    Subscriber      *User   `json:"subscriber"`
    Event           *Event  `json:"event"`
    SubscribedToUser *User  `json:"subscribedToUser"`
}


type User struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Email         string          `json:"email"`
	Subscriptions []*Subscription `json:"subscriptions"`
}
